---
# tasks file for git
- name: Add git ppa repository
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
