---
# tasks file for git
- name: Add git ppa repository
  ansible.builtin.deb822_repository:
    name: ppa:git-core/ppa
    state: present
    types: [deb]
    uris: "http://ppa.launchpad.net/mozillateam/ppa/ubuntu"
    suites: ["{{ ansible_distribution_release|lower }}"]
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0xF911AB184317630C59970973E363C90F8F1B6217"
    enabled: yes
  when: ansible_distribution == 'Ubuntu'
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
